// Use emotion's jsx function instead of React's - we need this to make use of the 'css' prop.
/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, useTheme } from "@emotion/react";
import Head from "next/head";

export default function Home() {
  const theme = useTheme();

  return (
    <div
      css={{
        background:
          "linear-gradient(104deg, #1e0505 2%,#380400 27%,#800000 68%,#cc2c00 100%)",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        minHeight: "100vh",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        css={{
          padding: "32px",
          maxWidth: "768px",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <img
          css={{
            width: "50%",
            marginBottom: "48px",
          }}
          src="https://ichef.bbci.co.uk/images/ic/raw/p0bx2qpy.png"
        />
        <h1
          css={{
            fontSize: "44px",
            color: "#fefefe",
            marginTop: "0",
            marginBottom: "32px",
          }}
        >
          Your world of Sounds
        </h1>
        <p
          style={{
            fontSize: "16px",
            color: "#fefefe",
            textAlign: "center",
            marginTop: "0",
            marginBottom: "32px",
          }}
        >
          Save shows to listen to later, subscribe to your favourites and get
          fresh recommendations every day.
        </p>
        <button
          css={{
            width: "300px",
            height: "48px",
            border: "none",
            background: theme.colors.live.core,
            color: "white",
            fontSize: "18px",
            fontWeight: "700",
            transition: "300ms",
            marginBottom: "8px",
            "&:hover, &:focus": {
              transform: "scale(1.05)",
              background: theme.colors.live.dark,
              cursor: "pointer",
            }
          }}
        >
          Listen Live
        </button>
        <button
          css={{
            width: "300px",
            height: "48px",
            border: "none",
            background: "#fa6400",
            color: "white",
            fontSize: "18px",
            fontWeight: "700",
            transition: "300ms",
            "&:hover, &:focus": {
              transform: "scale(1.05)",
              background: "#d24712",
              cursor: "pointer",
            }
          }}
        >
          Play
        </button>
      </main>
    </div>
  );
}
